export default {
  bossTreasure1: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure2: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure3: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure4: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure5: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure6: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure7: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure8: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure9: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure10: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure11: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure12: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure13: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure14: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure15: { item: 'Big Bag of gold ', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll three d20s' },
  bossTreasure16: { item: 'Twin Swords', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure17: { item: 'Twin Swords', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure18: { item: 'Twin Swords', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure19: { item: 'Saber and Flintlock Pistol', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure20: { item: 'Saber and Flintlock Pistol', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure21: { item: 'Saber and Flintlock Pistol', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure22: { item: 'Longsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure23: { item: 'Longsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure24: { item: 'Longsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure25: { item: 'Shortsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure26: { item: 'Shortsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure27: { item: 'Shortsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure28: { item: 'Greatsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure29: { item: 'Greatsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure30: { item: 'Greatsword', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure31: { item: 'Battleaxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure32: { item: 'Battleaxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure33: { item: 'Battleaxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure34: { item: 'Handaxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure35: { item: 'Handaxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure36: { item: 'Handaxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure37: { item: 'Greataxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure38: { item: 'Greataxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure39: { item: 'Greataxe', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure40: { item: 'Spear', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure41: { item: 'Spear', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure42: { item: 'Spear', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure43: { item: 'Javelin', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure44: { item: 'Javelin', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure45: { item: 'Javelin', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure46: { item: 'Halberd', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure47: { item: 'Halberd', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure48: { item: 'Halberd', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure49: { item: 'Warhammer', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure50: { item: 'Warhammer', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure51: { item: 'Warhammer', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure52: { item: 'Hammer', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure53: { item: 'Hammer', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure54: { item: 'Hammer', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure55: { item: 'Maul', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure56: { item: 'Maul', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure57: { item: 'Maul', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure58: { item: 'Shield (enchanted - (1 effect only not dodge/skill)', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure59: { item: 'Shield (enchanted - (1 effect only not dodge/skill)', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure60: { item: 'Shield (enchanted - (1 effect only not dodge/skill)', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure61: { item: 'Dagger', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure62: { item: 'Dagger', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure63: { item: 'Dagger', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure64: { item: 'Crossbow', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure65: { item: 'Crossbow', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure66: { item: 'Crossbow', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure67: { item: 'Shortbow', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure68: { item: 'Shortbow', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure69: { item: 'Shortbow', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure70: { item: 'Musket', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure71: { item: 'Musket', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure72: { item: 'Musket', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure73: { item: 'Wand', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure74: { item: 'Wand', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure75: { item: 'Wand', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure76: { item: 'Staff', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure77: { item: 'Staff', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure78: { item: 'Staff', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure79: { item: 'Orb', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure80: { item: 'Orb', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure81: { item: 'Orb', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure82: { item: 'Skull', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure83: { item: 'Skull', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure84: { item: 'Skull', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: true, action: null },
  bossTreasure85: { item: 'Charm', quantity: 1, modifier: { stat: 'Charm', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure86: { item: 'Charm', quantity: 1, modifier: { stat: 'Charm', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure87: { item: 'Charm', quantity: 1, modifier: { stat: 'Charm', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure88: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure89: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure90: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure91: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure92: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure93: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure94: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure95: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure96: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure97: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure98: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure99: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
  bossTreasure100: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
}
