export default {
  bossTreasure1: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure2: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure3: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure4: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure5: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure6: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure7: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure8: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure9: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure10: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure11: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure12: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure13: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure14: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure15: { item: 'Big Bag of gold ', isEnchanted: false, action: 'Roll three d20s'},
  bossTreasure16: { item: 'Twin Swords', isEnchanted: true, action: 'null'},
  bossTreasure17: { item: 'Twin Swords', isEnchanted: true, action: 'null'},
  bossTreasure18: { item: 'Twin Swords', isEnchanted: true, action: 'null'},
  bossTreasure19: { item: 'Saber and Flintlock Pistol', isEnchanted: true, action: 'null'},
  bossTreasure20: { item: 'Saber and Flintlock Pistol', isEnchanted: true, action: 'null'},
  bossTreasure21: { item: 'Saber and Flintlock Pistol', isEnchanted: true, action: 'null'},
  bossTreasure22: { item: 'Longsword', isEnchanted: true, action: 'null'},
  bossTreasure23: { item: 'Longsword', isEnchanted: true, action: 'null'},
  bossTreasure24: { item: 'Longsword', isEnchanted: true, action: 'null'},
  bossTreasure25: { item: 'Shortsword', isEnchanted: true, action: 'null'},
  bossTreasure26: { item: 'Shortsword', isEnchanted: true, action: 'null'},
  bossTreasure27: { item: 'Shortsword', isEnchanted: true, action: 'null'},
  bossTreasure28: { item: 'Greatsword', isEnchanted: true, action: 'null'},
  bossTreasure29: { item: 'Greatsword', isEnchanted: true, action: 'null'},
  bossTreasure30: { item: 'Greatsword', isEnchanted: true, action: 'null'},
  bossTreasure31: { item: 'Battleaxe', isEnchanted: true, action: 'null'},
  bossTreasure32: { item: 'Battleaxe', isEnchanted: true, action: 'null'},
  bossTreasure33: { item: 'Battleaxe', isEnchanted: true, action: 'null'},
  bossTreasure34: { item: 'Handaxe', isEnchanted: true, action: 'null'},
  bossTreasure35: { item: 'Handaxe', isEnchanted: true, action: 'null'},
  bossTreasure36: { item: 'Handaxe', isEnchanted: true, action: 'null'},
  bossTreasure37: { item: 'Greataxe', isEnchanted: true, action: 'null'},
  bossTreasure38: { item: 'Greataxe', isEnchanted: true, action: 'null'},
  bossTreasure39: { item: 'Greataxe', isEnchanted: true, action: 'null'},
  bossTreasure40: { item: 'Spear', isEnchanted: true, action: 'null'},
  bossTreasure41: { item: 'Spear', isEnchanted: true, action: 'null'},
  bossTreasure42: { item: 'Spear', isEnchanted: true, action: 'null'},
  bossTreasure43: { item: 'Javelin', isEnchanted: true, action: 'null'},
  bossTreasure44: { item: 'Javelin', isEnchanted: true, action: 'null'},
  bossTreasure45: { item: 'Javelin', isEnchanted: true, action: 'null'},
  bossTreasure46: { item: 'Halberd', isEnchanted: true, action: 'null'},
  bossTreasure47: { item: 'Halberd', isEnchanted: true, action: 'null'},
  bossTreasure48: { item: 'Halberd', isEnchanted: true, action: 'null'},
  bossTreasure49: { item: 'Warhammer', isEnchanted: true, action: 'null'},
  bossTreasure50: { item: 'Warhammer', isEnchanted: true, action: 'null'},
  bossTreasure51: { item: 'Warhammer', isEnchanted: true, action: 'null'},
  bossTreasure52: { item: 'Hammer', isEnchanted: true, action: 'null'},
  bossTreasure53: { item: 'Hammer', isEnchanted: true, action: 'null'},
  bossTreasure54: { item: 'Hammer', isEnchanted: true, action: 'null'},
  bossTreasure55: { item: 'Maul', isEnchanted: true, action: 'null'},
  bossTreasure56: { item: 'Maul', isEnchanted: true, action: 'null'},
  bossTreasure57: { item: 'Maul', isEnchanted: true, action: 'null'},
  bossTreasure58: { item: 'Shield (enchanted - (1 effect only not dodge/skill)', isEnchanted: true, action: 'null'},
  bossTreasure59: { item: 'Shield (enchanted - (1 effect only not dodge/skill)', isEnchanted: true, action: 'null'},
  bossTreasure60: { item: 'Shield (enchanted - (1 effect only not dodge/skill)', isEnchanted: true, action: 'null'},
  bossTreasure61: { item: 'Dagger', isEnchanted: true, action: 'null'},
  bossTreasure62: { item: 'Dagger', isEnchanted: true, action: 'null'},
  bossTreasure63: { item: 'Dagger', isEnchanted: true, action: 'null'},
  bossTreasure64: { item: 'Crossbow', isEnchanted: true, action: 'null'},
  bossTreasure65: { item: 'Crossbow', isEnchanted: true, action: 'null'},
  bossTreasure66: { item: 'Crossbow', isEnchanted: true, action: 'null'},
  bossTreasure67: { item: 'Shortbow', isEnchanted: true, action: 'null'},
  bossTreasure68: { item: 'Shortbow', isEnchanted: true, action: 'null'},
  bossTreasure69: { item: 'Shortbow', isEnchanted: true, action: 'null'},
  bossTreasure70: { item: 'Musket', isEnchanted: true, action: 'null'},
  bossTreasure71: { item: 'Musket', isEnchanted: true, action: 'null'},
  bossTreasure72: { item: 'Musket', isEnchanted: true, action: 'null'},
  bossTreasure73: { item: 'Wand', isEnchanted: true, action: 'null'},
  bossTreasure74: { item: 'Wand', isEnchanted: true, action: 'null'},
  bossTreasure75: { item: 'Wand', isEnchanted: true, action: 'null'},
  bossTreasure76: { item: 'Staff', isEnchanted: true, action: 'null'},
  bossTreasure77: { item: 'Staff', isEnchanted: true, action: 'null'},
  bossTreasure78: { item: 'Staff', isEnchanted: true, action: 'null'},
  bossTreasure79: { item: 'Orb', isEnchanted: true, action: 'null'},
  bossTreasure80: { item: 'Orb', isEnchanted: true, action: 'null'},
  bossTreasure81: { item: 'Orb', isEnchanted: true, action: 'null'},
  bossTreasure82: { item: 'Skull', isEnchanted: true, action: 'null'},
  bossTreasure83: { item: 'Skull', isEnchanted: true, action: 'null'},
  bossTreasure84: { item: 'Skull', isEnchanted: true, action: 'null'},
  bossTreasure85: { item: 'Charm: Body +2', isEnchanted: false, action: 'null'},
  bossTreasure86: { item: 'Charm: Body +2', isEnchanted: false, action: 'null'},
  bossTreasure87: { item: 'Charm: Body +2', isEnchanted: false, action: 'null'},
  bossTreasure88: { item: 'Charm: Mind +2', isEnchanted: false, action: 'null'},
  bossTreasure89: { item: 'Charm: Mind +2', isEnchanted: false, action: 'null'},
  bossTreasure90: { item: 'Charm: Mind +2', isEnchanted: false, action: 'null'},
  bossTreasure91: { item: 'Charm: Skill +2', isEnchanted: false, action: 'null'},
  bossTreasure92: { item: 'Charm: Skill +2', isEnchanted: false, action: 'null'},
  bossTreasure93: { item: 'Charm: Skill +2', isEnchanted: false, action: 'null'},
  bossTreasure94: { item: 'Charm: Will +2', isEnchanted: false, action: 'null'},
  bossTreasure95: { item: 'Charm: Will +2', isEnchanted: false, action: 'null'},
  bossTreasure96: { item: 'Charm: Will +2', isEnchanted: false, action: 'null'},
  bossTreasure97: { item: 'Charm: Luck +2', isEnchanted: false, action: 'null'},
  bossTreasure98: { item: 'Charm: Luck +2', isEnchanted: false, action: 'null'},
  bossTreasure99: { item: 'Charm: Luck +2', isEnchanted: false, action: 'null'},
  bossTreasure100: { item: 'Charm: Luck +2', isEnchanted: false, action: 'null'},
}
