export default {
  treasure1: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure2: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure3: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure4: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure5: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure6: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure7: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure8: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure9: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure10: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure11: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure12: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure13: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure14: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure15: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure16: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure17: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure18: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure19: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure20: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure21: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure22: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure23: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure24: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure25: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure26: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure27: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure28: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure29: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure30: { item: 'Bag of gold', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: 'Roll one d20' },
  treasure31: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure32: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure33: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure34: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure35: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure36: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure37: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure38: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure39: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure40: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure41: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure42: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure43: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure44: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure45: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure46: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure47: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure48: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure49: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure50: { item: 'Healing Draught', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure51: { item: 'Lock-pick', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure52: { item: 'Lock-pick', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure53: { item: 'Lock-pick', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure54: { item: 'Lock-pick', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure55: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure56: { item: 'Smoke Bomb', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure57: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure58: { item: 'Skill Potion', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure59: { item: 'Skill Potion', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure60: { item: 'Skill Potion', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure61: { item: 'Trinket: Attack+1', quantity: 1, modifier: { stat: 'Attack', amount: 1 }, isEnchanted: false, action: null },
  treasure62: { item: 'Trinket: Attack+2', quantity: 1, modifier: { stat: 'Attack', amount: 2 }, isEnchanted: false, action: null },
  treasure63: { item: 'Trinket: Dodge+1', quantity: 1, modifier: { stat: 'Dodge', amount: 1 }, isEnchanted: false, action: null },
  treasure64: { item: 'Trinket: Dodge+2', quantity: 1, modifier: { stat: 'Dodge', amount: 2 }, isEnchanted: false, action: null },
  treasure65: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure66: { item: 'Trinket: Block+1', quantity: 1, modifier: { stat: 'Block', amount: 1 }, isEnchanted: false, action: null },
  treasure67: { item: 'Trinket: Block+2', quantity: 1, modifier: { stat: 'Block', amount: 2 }, isEnchanted: false, action: null },
  treasure68: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure69: { item: 'Poison Ammo', quantity: 3, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure70: { item: 'Holy Ammo', quantity: 3, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure71: { item: 'Shield', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure72: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure73: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure74: { item: 'Ethereal Ammo', quantity: 3, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure75: { item: 'Explosive Ammo', quantity: 3, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure76: { item: 'Bio Ammo', quantity: 3, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure77: { item: 'Fermented Apple', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure78: { item: 'Chain armor', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure79: { item: 'Leather Helmet', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure80: { item: 'Iron Helmet', quantity: 1, modifier: { stat: null, amount: null }, isEnchanted: false, action: null },
  treasure81: { item: 'Charm', quantity: 1, modifier: { stat: 'Body', amount: 2 }, isEnchanted: false, action: null },
  treasure82: { item: 'Charm', quantity: 1, modifier: { stat: 'Body', amount: 2 }, isEnchanted: false, action: null },
  treasure83: { item: 'Charm', quantity: 1, modifier: { stat: 'Body', amount: 2 }, isEnchanted: false, action: null },
  treasure84: { item: 'Charm', quantity: 1, modifier: { stat: 'Body', amount: 2 }, isEnchanted: false, action: null },
  treasure85: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  treasure86: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  treasure87: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  treasure88: { item: 'Charm', quantity: 1, modifier: { stat: 'Mind', amount: 2 }, isEnchanted: false, action: null },
  treasure89: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  treasure90: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  treasure91: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  treasure92: { item: 'Charm', quantity: 1, modifier: { stat: 'Skill', amount: 2 }, isEnchanted: false, action: null },
  treasure93: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  treasure94: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  treasure95: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  treasure96: { item: 'Charm', quantity: 1, modifier: { stat: 'Will', amount: 2 }, isEnchanted: false, action: null },
  treasure97: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
  treasure98: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
  treasure99: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
  treasure100: { item: 'Charm', quantity: 1, modifier: { stat: 'Luck', amount: 2 }, isEnchanted: false, action: null },
}
