export default {
  treasure1: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure2: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure3: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure4: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure5: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure6: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure7: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure8: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure9: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure10: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure11: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure12: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure13: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure14: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure15: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure16: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure17: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure18: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure19: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure20: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure21: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure22: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure23: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure24: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure25: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure26: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure27: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure28: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure29: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure30: { item: 'Bag of gold ', isEnchanted: false, action: 'Roll one d20'},
  treasure31: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure32: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure33: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure34: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure35: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure36: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure37: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure38: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure39: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure40: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure41: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure42: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure43: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure44: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure45: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure46: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure47: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure48: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure49: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure50: { item: 'Healing Draught', isEnchanted: false, action: 'null'},
  treasure51: { item: 'Lock-pick', isEnchanted: false, action: 'null'},
  treasure52: { item: 'Lock-pick', isEnchanted: false, action: 'null'},
  treasure53: { item: 'Lock-pick', isEnchanted: false, action: 'null'},
  treasure54: { item: 'Lock-pick', isEnchanted: false, action: 'null'},
  treasure55: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure56: { item: 'Smoke Bomb', isEnchanted: false, action: 'null'},
  treasure57: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure58: { item: 'Skill Potion', isEnchanted: false, action: 'null'},
  treasure59: { item: 'Skill Potion', isEnchanted: false, action: 'null'},
  treasure60: { item: 'Skill Potion', isEnchanted: false, action: 'null'},
  treasure61: { item: 'Trinket: Attack+1', isEnchanted: false, action: 'null'},
  treasure62: { item: 'Trinket: Attack+2', isEnchanted: false, action: 'null'},
  treasure63: { item: 'Trinket: Dodge+1', isEnchanted: false, action: 'null'},
  treasure64: { item: 'Trinket: Dodge+2', isEnchanted: false, action: 'null'},
  treasure65: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure66: { item: 'Trinket: Block+1', isEnchanted: false, action: 'null'},
  treasure67: { item: 'Trinket: Block+2', isEnchanted: false, action: 'null'},
  treasure68: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure69: { item: 'Poison Ammo x 3', isEnchanted: false, action: 'null'},
  treasure70: { item: 'Holy Ammo x 3', isEnchanted: false, action: 'null'},
  treasure71: { item: 'Shield', isEnchanted: false, action: 'null'},
  treasure72: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure73: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure74: { item: 'Ethereal Ammo x 3', isEnchanted: false, action: 'null'},
  treasure75: { item: 'Explosive Ammo x 3', isEnchanted: false, action: 'null'},
  treasure76: { item: 'Bio Ammo x 3', isEnchanted: false, action: 'null'},
  treasure77: { item: 'Fermented Apple', isEnchanted: false, action: 'null'},
  treasure78: { item: 'Chain armor', isEnchanted: false, action: 'null'},
  treasure79: { item: 'Leather Helmet', isEnchanted: false, action: 'null'},
  treasure80: { item: 'Iron Helmet', isEnchanted: false, action: 'null'},
  treasure81: { item: 'Charm: Body+2', isEnchanted: false, action: 'null'},
  treasure82: { item: 'Charm: Body+2', isEnchanted: false, action: 'null'},
  treasure83: { item: 'Charm: Body+2', isEnchanted: false, action: 'null'},
  treasure84: { item: 'Charm: Body+2', isEnchanted: false, action: 'null'},
  treasure85: { item: 'Charm: Mind+2', isEnchanted: false, action: 'null'},
  treasure86: { item: 'Charm: Mind+2', isEnchanted: false, action: 'null'},
  treasure87: { item: 'Charm: Mind+2', isEnchanted: false, action: 'null'},
  treasure88: { item: 'Charm: Mind+2', isEnchanted: false, action: 'null'},
  treasure89: { item: 'Charm: Skill+2', isEnchanted: false, action: 'null'},
  treasure90: { item: 'Charm: Skill+2', isEnchanted: false, action: 'null'},
  treasure91: { item: 'Charm: Skill+2', isEnchanted: false, action: 'null'},
  treasure92: { item: 'Charm: Skill+2', isEnchanted: false, action: 'null'},
  treasure93: { item: 'Charm: Will+2', isEnchanted: false, action: 'null'},
  treasure94: { item: 'Charm: Will+2', isEnchanted: false, action: 'null'},
  treasure95: { item: 'Charm: Will+2', isEnchanted: false, action: 'null'},
  treasure96: { item: 'Charm: Will+2', isEnchanted: false, action: 'null'},
  treasure97: { item: 'Charm: Luck+2', isEnchanted: false, action: 'null'},
  treasure98: { item: 'Charm: Luck+2', isEnchanted: false, action: 'null'},
  treasure99: { item: 'Charm: Luck+2', isEnchanted: false, action: 'null'},
  treasure100: { item: 'Charm: Luck+2', isEnchanted: false, action: 'null'},
}
